<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductoSeeder extends Seeder
{
    public function run()
    {
        $productos = [
            [
                'codigo' => '14445414126',
                'nombre_producto' => 'Inca kola familiar',
                'descripcion_producto' => 'Gaseosa Inka Cola en presentación de 3L',
                'stock' => 110,
                'stock_minimo' => 30,
                'stock_maximo' => 120,
                'precio_compra' => 9.00,
                'precio_venta' => 11.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'inca-kola-3l.jpg',
                'id_categoria' => 3,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '11447569872',
                'nombre_producto' => 'Inca Kola personal',
                'descripcion_producto' => 'Gaseosa Inca Kola en presentación de 500ml',
                'stock' => 200,
                'stock_minimo' => 30,
                'stock_maximo' => 300,
                'precio_compra' => 2.00,
                'precio_venta' => 2.50,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'inca-kola-500ml.jpg',
                'id_categoria' => 3,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '15447896542',
                'nombre_producto' => 'Coca Cola familiar',
                'descripcion_producto' => 'Gaseosa Coca Cola en presentación de 3L',
                'stock' => 120,
                'stock_minimo' => 24,
                'stock_maximo' => 150,
                'precio_compra' => 9.00,
                'precio_venta' => 11.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'coca-cola-3l.jpg',
                'id_categoria' => 3,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '15874214574',
                'nombre_producto' => 'Coca Cola personal',
                'descripcion_producto' => 'Gaseosa Coca Cola en presentación de 500 ml',
                'stock' => 200,
                'stock_minimo' => 30,
                'stock_maximo' => 300,
                'precio_compra' => 2.00,
                'precio_venta' => 2.50,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'coca-cola-500ml.jpg',
                'id_categoria' => 3,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '15742158741',
                'nombre_producto' => 'Sprite familiar',
                'descripcion_producto' => 'Gaseosa Sprite en presentación de 3L',
                'stock' => 110,
                'stock_minimo' => 20,
                'stock_maximo' => 200,
                'precio_compra' => 6.50,
                'precio_venta' => 8.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'sprite-3l.jpg',
                'id_categoria' => 3,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '15874214539',
                'nombre_producto' => 'Sprite personal',
                'descripcion_producto' => 'Gaseosa Sprite en presentación de 500ml',
                'stock' => 200,
                'stock_minimo' => 30,
                'stock_maximo' => 300,
                'precio_compra' => 1.80,
                'precio_venta' => 2.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'sprite-500ml.jpg',
                'id_categoria' => 3,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '17484211474',
                'nombre_producto' => 'Fanta Naranja familiar',
                'descripcion_producto' => 'Gaseosa Fanta Naranja en presentación de 3L',
                'stock' => 130,
                'stock_minimo' => 20,
                'stock_maximo' => 200,
                'precio_compra' => 8.00,
                'precio_venta' => 9.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'fanta-naranja-3l.jpg',
                'id_categoria' => 3,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '18547414111',
                'nombre_producto' => 'Fanta Naranja personal',
                'descripcion_producto' => 'Gaseosa Fanta Naranja en presentación de 500ml',
                'stock' => 200,
                'stock_minimo' => 50,
                'stock_maximo' => 300,
                'precio_compra' => 1.80,
                'precio_venta' => 2.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'fanta-naranja-500ml.jpg',
                'id_categoria' => 3,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '15774214114',
                'nombre_producto' => 'Pepsi familiar',
                'descripcion_producto' => 'Gaseosa Pepsi en presentación de 3L',
                'stock' => 160,
                'stock_minimo' => 40,
                'stock_maximo' => 250,
                'precio_compra' => 7.00,
                'precio_venta' => 8.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'Pepsi-3L.jpg',
                'id_categoria' => 3,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '1742224524',
                'nombre_producto' => 'Pepsi personal',
                'descripcion_producto' => 'Gaseosa Pepsi en presentación de 500ml',
                'stock' => 200,
                'stock_minimo' => 30,
                'stock_maximo' => 300,
                'precio_compra' => 1.50,
                'precio_venta' => 1.80,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'Pepsi-500ml.jpg',
                'id_categoria' => 3,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '14423665456',
                'nombre_producto' => 'Jugo Del Valle',
                'descripcion_producto' => 'Jugo Del Valle en presentación de 500ml',
                'stock' => 160,
                'stock_minimo' => 30,
                'stock_maximo' => 200,
                'precio_compra' => 1.20,
                'precio_venta' => 1.50,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'valle-500ml.jpg',
                'id_categoria' => 3,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '11474599852',
                'nombre_producto' => 'Agua San Luis',
                'descripcion_producto' => 'Agua mineral San Luis en presentación de 600ml',
                'stock' => 300,
                'stock_minimo' => 60,
                'stock_maximo' => 400,
                'precio_compra' =>1.50,
                'precio_venta' => 2.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'san-luis-600ml.jpg',
                'id_categoria' => 3,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '15474147521',
                'nombre_producto' => 'Agua San Luis',
                'descripcion_producto' => 'Agua mineral San Luis en presentación de 600ml',
                'stock' => 300,
                'stock_minimo' => 60,
                'stock_maximo' => 400,
                'precio_compra' =>1.50,
                'precio_venta' => 2.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'san-luis-600ml.jpg',
                'id_categoria' => 3,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '15547269852',
                'nombre_producto' => 'Cerbeza Pilsen Callao',
                'descripcion_producto' => 'Cerbeza Pilsen Callao en presentación de 620ml',
                'stock' => 200,
                'stock_minimo' => 50,
                'stock_maximo' => 300,
                'precio_compra' => 4.50,
                'precio_venta' => 5.50,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'pilsen-620ml.jpg',
                'id_categoria' => 10,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '18774154212',
                'nombre_producto' => 'Cerbeza Cristal',
                'descripcion_producto' => 'Cerbeza Cristal en presentación de 620ml',
                'stock' => 200,
                'stock_minimo' => 50,
                'stock_maximo' => 300,
                'precio_compra' => 4.50,
                'precio_venta' => 5.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'cristal-620ml.jpg',
                'id_categoria' => 10,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '17441147598',
                'nombre_producto' => 'Cerbeza Cusqueña',
                'descripcion_producto' => 'Cerbeza Cusqueña en presentación de 500ml',
                'stock' => 150,
                'stock_minimo' => 30,
                'stock_maximo' => 200,
                'precio_compra' => 5.00,
                'precio_venta' => 6.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'cusqueña-620ml.jpg',
                'id_categoria' => 10,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '19887411414',
                'nombre_producto' => 'Red Bull',
                'descripcion_producto' => 'Energizante Red Bull en presentación de 500ml',
                'stock' => 80,
                'stock_minimo' => 20,
                'stock_maximo' => 200,
                'precio_compra' => 6.50,
                'precio_venta' => 7.50,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'red-500ml.jpg',
                'id_categoria' => 3,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '11144425474',
                'nombre_producto' => 'Sporade',
                'descripcion_producto' => 'Sporade Tropical en presentación de 500ml',
                'stock' => 200,
                'stock_minimo' => 50,
                'stock_maximo' => 250,
                'precio_compra' => 2.00,
                'precio_venta' => 2.50,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'sporade-500ml.jpg',
                'id_categoria' => 3,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '25474157587',
                'nombre_producto' => 'Leche Gloria',
                'descripcion_producto' => 'Leche Gloria en bolsa presentación de 1L',
                'stock' => 60,
                'stock_minimo' => 24,
                'stock_maximo' => 100,
                'precio_compra' => 2.50,
                'precio_venta' => 3.50,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'leche-gloria-3l.jpg',
                'id_categoria' => 2,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '2547415874',
                'nombre_producto' => ' Leche Laive',
                'descripcion_producto' => 'Leche Laive en bolsa presentación de 1L',
                'stock' => 70,
                'stock_minimo' => 24,
                'stock_maximo' => 100,
                'precio_compra' => 2.50,
                'precio_venta' => 3.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'leche-laive-3l.jpg',
                'id_categoria' => 2,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '22441412568',
                'nombre_producto' => 'Mantequilla Laive',
                'descripcion_producto' => 'Mantequilla Laive de fresa de 200g',
                'stock' => 120,
                'stock_minimo' => 30,
                'stock_maximo' => 150,
                'precio_compra' => 2.50,
                'precio_venta' => 3.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'mantequilla-laive-200g.jpg',
                'id_categoria' => 2,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '22441412568',
                'nombre_producto' => 'Fideos Don Vittorio',
                'descripcion_producto' => 'Fideo grueso Don Vittorio de 1kg',
                'stock' => 90,
                'stock_minimo' => 20,
                'stock_maximo' => 200,
                'precio_compra' => 5.00,
                'precio_venta' => 5.50,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'fideo-vittorio-1kg.jpg',
                'id_categoria' => 1,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '22441412568',
                'nombre_producto' => 'Arroz Costeño',
                'descripcion_producto' => 'Arroz Costeño de 1kg',
                'stock' => 120,
                'stock_minimo' => 30,
                'stock_maximo' => 200,
                'precio_compra' => 3.00,
                'precio_venta' => 3.60,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'arroz-costeño-1kg.jpg',
                'id_categoria' => 1,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '25544741587',
                'nombre_producto' => 'Azucar blanca Dulfina',
                'descripcion_producto' => 'Azucar blanca de 1kg',
                'stock' => 100,
                'stock_minimo' => 30,
                'stock_maximo' => 200,
                'precio_compra' => 3.00,
                'precio_venta' => 3.20,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'azucar-blanca-1kg.jpg',
                'id_categoria' => 1,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '25587741414',
                'nombre_producto' => 'Azucar rubia Dulfina',
                'descripcion_producto' => 'Azucar rubia de 1kg',
                'stock' => 150,
                'stock_minimo' => 50,
                'stock_maximo' => 300,
                'precio_compra' => 2.80,
                'precio_venta' => 3.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'azucar-rubia-1kg.jpg',
                'id_categoria' => 1,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '35587474145',
                'nombre_producto' => 'Aceite vegetal Primor',
                'descripcion_producto' => 'Aceite vegetal de 1L',
                'stock' => 90,
                'stock_minimo' => 120,
                'stock_maximo' => 200,
                'precio_compra' => 9.50,
                'precio_venta' => 10.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'aceite-primor-1l.jpg',
                'id_categoria' => 1,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '35442574151',
                'nombre_producto' => 'Aceite vegetal Cocinero',
                'descripcion_producto' => 'Aceite vegetal de 1L',
                'stock' => 100,
                'stock_minimo' => 120,
                'stock_maximo' => 200,
                'precio_compra' => 9.00,
                'precio_venta' => 9.50,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'aceite-cocinero-1l.jpg',
                'id_categoria' => 1,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '57744147585',
                'nombre_producto' => 'Lentegitas Costeño',
                'descripcion_producto' => 'Lentegitas Costeño de 1kg',
                'stock' => 60,
                'stock_minimo' => 20,
                'stock_maximo' => 120,
                'precio_compra' => 3.50,
                'precio_venta' => 4.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'lenteja-1kg.jpg',
                'id_categoria' => 1,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '58874147511',
                'nombre_producto' => 'Arvejas Costeño',
                'descripcion_producto' => 'Arvejas Costeño de 1kg',
                'stock' => 50,
                'stock_minimo' => 20,
                'stock_maximo' => 120,
                'precio_compra' => 3.50,
                'precio_venta' => 4.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'arveja-1kg.jpg',
                'id_categoria' => 1,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '41414759632',
                'nombre_producto' => 'Pan de molde Bimbo',
                'descripcion_producto' => 'Pan de molde Bimbo de 900g',
                'stock' => 60,
                'stock_minimo' => 12,
                'stock_maximo' => 100,
                'precio_compra' => 10.00,
                'precio_venta' => 11.50,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'bimbo-900g.jpg',
                'id_categoria' => 1,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '58474147452',
                'nombre_producto' => 'Galletas Club Social',
                'descripcion_producto' => 'Galletas Club Social de 24g',
                'stock' => 120,
                'stock_minimo' => 30,
                'stock_maximo' => 250,
                'precio_compra' => 0.70,
                'precio_venta' => 1.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'social-24g.jpg',
                'id_categoria' => 4,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '65414414587',
                'nombre_producto' => 'Galleta Óreo',
                'descripcion_producto' => 'Galleta Óreo de 36g',
                'stock' => 80,
                'stock_minimo' => 30,
                'stock_maximo' => 180,
                'precio_compra' => 0.80,
                'precio_venta' => 1.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'oreo-36g.jpg',
                'id_categoria' => 4,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '65568756541',
                'nombre_producto' => 'Galleta Picaras',
                'descripcion_producto' => 'Galleta Picaras de 30g',
                'stock' => 70,
                'stock_minimo' => 30,
                'stock_maximo' => 120,
                'precio_compra' => 0.80,
                'precio_venta' => 1.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'picaras-30g.jpg',
                'id_categoria' => 4,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '58741475415',
                'nombre_producto' => 'Chocolate Sublime',
                'descripcion_producto' => 'Chocolate Sublime de 30g',
                'stock' => 60,
                'stock_minimo' => 20,
                'stock_maximo' => 100,
                'precio_compra' => 1.80,
                'precio_venta' => 2.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'sublime-30g.jpg',
                'id_categoria' => 4,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '45774147596',
                'nombre_producto' => 'Galleta vainilla GN',
                'descripcion_producto' => 'Galleta vainilla GN de 30g',
                'stock' => 120,
                'stock_minimo' => 30,
                'stock_maximo' => 200,
                'precio_compra' => 0.50,
                'precio_venta' => 0.70,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'gn-30g.jpg',
                'id_categoria' => 4,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '44745898521',
                'nombre_producto' => 'Galleta soda San Jorge',
                'descripcion_producto' => 'Galleta soda San Jorge de 40g',
                'stock' => 150,
                'stock_minimo' => 40,
                'stock_maximo' => 200,
                'precio_compra' => 0.70,
                'precio_venta' => 1.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'jorge-40g.jpg',
                'id_categoria' => 4,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '45774147592',
                'nombre_producto' => 'Mayonesa A la Cena',
                'descripcion_producto' => 'Mayonesa A la Cena de 250g',
                'stock' => 90,
                'stock_minimo' => 20,
                'stock_maximo' => 100,
                'precio_compra' => 4.50,
                'precio_venta' => 5.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'mayonesa-250g.jpg',
                'id_categoria' => 1,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '66548587452',
                'nombre_producto' => 'Detergente Ace',
                'descripcion_producto' => 'Detergente Ace de 1kg',
                'stock' => 100,
                'stock_minimo' => 30,
                'stock_maximo' => 200,
                'precio_compra' => 7.50,
                'precio_venta' => 8.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'ace-250g.jpg',
                'id_categoria' => 6,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '65485456542',
                'nombre_producto' => 'Detergente Ariel',
                'descripcion_producto' => 'Detergente Ariel de 1kg',
                'stock' => 90,
                'stock_minimo' => 35,
                'stock_maximo' => 200,
                'precio_compra' => 8.00,
                'precio_venta' => 9.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'ariel-250g.jpg',
                'id_categoria' => 6,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '61521669852',
                'nombre_producto' => 'Shampoo Head & Shoulders',
                'descripcion_producto' => 'Shampoo Head & Shoulders de 700ml',
                'stock' => 70,
                'stock_minimo' => 12,
                'stock_maximo' => 120,
                'precio_compra' => 9.00,
                'precio_venta' => 11.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'hs-700ml.jpg',
                'id_categoria' => 7,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '65456587459',
                'nombre_producto' => 'Shampoo Pantene',
                'descripcion_producto' => 'Shampoo Pantene de 700ml',
                'stock' => 70,
                'stock_minimo' => 12,
                'stock_maximo' => 120,
                'precio_compra' => 9.00,
                'precio_venta' => 10.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'pantene-700ml.jpg',
                'id_categoria' => 7,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '77454774141',
                'nombre_producto' => 'Papel higiénico Elite',
                'descripcion_producto' => 'Papel higiénico Elite de 2 rollos',
                'stock' => 90,
                'stock_minimo' => 24,
                'stock_maximo' => 100,
                'precio_compra' => 2.50,
                'precio_venta' => 3.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'papel.jpg',
                'id_categoria' => 7,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '85447458931',
                'nombre_producto' => 'Legía Clorox',
                'descripcion_producto' => 'Legía Clorox 500ml',
                'stock' => 60,
                'stock_minimo' => 20,
                'stock_maximo' => 100,
                'precio_compra' => 2.80,
                'precio_venta' => 3.20,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'clorox.jpg',
                'id_categoria' => 6,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '77747587451',
                'nombre_producto' => 'Huevos La Calera',
                'descripcion_producto' => 'Huevos La Calera de 15 ud',
                'stock' => 80,
                'stock_minimo' => 20,
                'stock_maximo' => 100,
                'precio_compra' => 5.50,
                'precio_venta' => 7.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'calera.jpg',
                'id_categoria' => 2,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '70745741584',
                'nombre_producto' => 'Lata de atún Primor',
                'descripcion_producto' => 'Lata de atún Primor de 170g',
                'stock' => 60,
                'stock_minimo' => 20,
                'stock_maximo' => 120,
                'precio_compra' => 3.50,
                'precio_venta' => 4.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'lata-atun-primor.jpg',
                'id_categoria' => 8,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '78985452142',
                'nombre_producto' => 'Lata de atún Campomar',
                'descripcion_producto' => 'Lata de atún Campomar de 200g',
                'stock' => 70,
                'stock_minimo' => 20,
                'stock_maximo' => 120,
                'precio_compra' => 3.50,
                'precio_venta' => 4.20,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'lata-atun-campomar.jpg',
                'id_categoria' => 8,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '85474587451',
                'nombre_producto' => 'Lata de leche condensada',
                'descripcion_producto' => 'Lata de leche condensada de 400g',
                'stock' => 90,
                'stock_minimo' => 30,
                'stock_maximo' => 100,
                'precio_compra' => 4.50,
                'precio_venta' => 5.30,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'condensada.jpg',
                'id_categoria' => 2,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '74157415784',
                'nombre_producto' => 'Café Nescafé',
                'descripcion_producto' => 'Café Nescafé de 200g',
                'stock' => 100,
                'stock_minimo' => 50,
                'stock_maximo' => 200,
                'precio_compra' => 2.80,
                'precio_venta' => 3.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'cafe.jpg',
                'id_categoria' => 1,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '70548741541',
                'nombre_producto' => 'Caja de té MC Colins',
                'descripcion_producto' => 'Caja de té MC Colins de 24 ud',
                'stock' => 120,
                'stock_minimo' => 50,
                'stock_maximo' => 200,
                'precio_compra' => 2.50,
                'precio_venta' => 3.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'te.jpg',
                'id_categoria' => 1,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '70548745163',
                'nombre_producto' => 'Caja de manzanilla MC Colins',
                'descripcion_producto' => 'Caja de manzanilla MC Colins de 24 ud',
                'stock' => 100,
                'stock_minimo' => 50,
                'stock_maximo' => 200,
                'precio_compra' => 2.50,
                'precio_venta' => 3.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'manzanilla.jpg',
                'id_categoria' => 1,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '77554874854',
                'nombre_producto' => 'Sazonador Ajinomoto',
                'descripcion_producto' => 'Sazonador Ajinomoto de 60g',
                'stock' => 120,
                'stock_minimo' => 30,
                'stock_maximo' => 200,
                'precio_compra' => 1.80,
                'precio_venta' => 2.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'ajinomoto.jpg',
                'id_categoria' => 1,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '58474414256',
                'nombre_producto' => 'Sopa instantánea de pollo Ajinomen',
                'descripcion_producto' => 'Sopa instantánea de pollo Ajinomen de 80g',
                'stock' => 120,
                'stock_minimo' => 30,
                'stock_maximo' => 200,
                'precio_compra' => 1.50,
                'precio_venta' => 1.80,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'pollo.jpg',
                'id_categoria' => 1,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '58554712698',
                'nombre_producto' => 'Sopa instantánea de carne Ajinomen',
                'descripcion_producto' => 'Sopa instantánea de carne Ajinomen de 80g',
                'stock' => 110,
                'stock_minimo' => 30,
                'stock_maximo' => 200,
                'precio_compra' => 1.50,
                'precio_venta' => 1.80,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'carne.jpg',
                'id_categoria' => 1,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '65158542514',
                'nombre_producto' => 'Pasta dental Colgate',
                'descripcion_producto' => 'Pasta dental Colgate de 60g',
                'stock' => 80,
                'stock_minimo' => 20,
                'stock_maximo' => 150,
                'precio_compra' => 3.30,
                'precio_venta' => 3.80,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'colgate.jpg',
                'id_categoria' => 7,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '60355874521',
                'nombre_producto' => 'Pasta dental Dento',
                'descripcion_producto' => 'Pasta dental Dento 65g',
                'stock' => 70,
                'stock_minimo' => 20,
                'stock_maximo' => 150,
                'precio_compra' => 3.50,
                'precio_venta' => 4.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'dento.jpg',
                'id_categoria' => 7,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '50257458412',
                'nombre_producto' => 'Cheetos',
                'descripcion_producto' => 'Cheetos picante de 26g',
                'stock' => 60,
                'stock_minimo' => 30,
                'stock_maximo' => 90,
                'precio_compra' => 1.20,
                'precio_venta' => 1.50,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'cheetos.jpg',
                'id_categoria' => 4,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '50257458412',
                'nombre_producto' => 'Lays',
                'descripcion_producto' => 'Lays de 24g',
                'stock' => 60,
                'stock_minimo' => 30,
                'stock_maximo' => 100,
                'precio_compra' => 1.80,
                'precio_venta' => 2.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'lays.jpg',
                'id_categoria' => 4,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '45784574125',
                'nombre_producto' => 'Doritos',
                'descripcion_producto' => 'Doritos naturales de 35g',
                'stock' => 90,
                'stock_minimo' => 30,
                'stock_maximo' => 150,
                'precio_compra' => 1.80,
                'precio_venta' => 2.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'doritos.jpg',
                'id_categoria' => 4,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '58547854745',
                'nombre_producto' => 'Tor-tees',
                'descripcion_producto' => 'Tor-tees naturales 71g',
                'stock' => 80,
                'stock_minimo' => 30,
                'stock_maximo' => 150,
                'precio_compra' => 1.80,
                'precio_venta' => 2.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'tortees.jpg',
                'id_categoria' => 4,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '58547854745',
                'nombre_producto' => 'Takis',
                'descripcion_producto' => 'Takis fuego 28g ',
                'stock' => 70,
                'stock_minimo' => 30,
                'stock_maximo' => 150,
                'precio_compra' => 4.50,
                'precio_venta' => 5.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'takis.jpg',
                'id_categoria' => 4,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '65847521485',
                'nombre_producto' => 'Yogurt Gloria',
                'descripcion_producto' => 'Yogurt Gloria de fresa 900ml',
                'stock' => 70,
                'stock_minimo' => 20,
                'stock_maximo' => 100,
                'precio_compra' => 4.50,
                'precio_venta' => 5.50,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'yogurtg.jpg',
                'id_categoria' => 2,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '70547854741',
                'nombre_producto' => 'Vino Borgoña',
                'descripcion_producto' => 'Vino Borgoña de 900ml',
                'stock' => 60,
                'stock_minimo' => 20,
                'stock_maximo' => 100,
                'precio_compra' => 12.00,
                'precio_venta' => 15.00,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'vino.jpg',
                'id_categoria' => 10,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codigo' => '80545241459',
                'nombre_producto' => 'Ricocan cachorro',
                'descripcion_producto' => 'Ricocan cachorro',
                'stock' => 50,
                'stock_minimo' => 10,
                'stock_maximo' => 90,
                'precio_compra' => 12.00,
                'precio_venta' => 12.90,
                'fecha_ingreso' => Carbon::now(),
                'imagen' => 'ricocan.jpg',
                'id_categoria' => 9,
                'id_usuario' => 7,
                'estadoproducto' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        DB::table('productos')->insert($productos);
    }
}
